### PR TITLE
Various Fixes from Animation Project

### PR DESCRIPTION
**Pull request by Menithal**
This is a patch for issues discovered during the EF Opening Ceremony 2022 Animation

- Version bump 2.1.2 now
- If Render was canceled, 
   - Fixes: the encoding plugin was applying normals in the preview window. 
   - Fixes: Modifiers were being  disabled per frame change
- The patch makes sure only the vcol attribute defined on the mesh is used as the normal storage, .  It was possible for the active vertex data to suddenly change causing a sudden memory exception
- Lessened the amount of variables used to transfer the normal data to color to vertex
- Some cleanup of color data during loops. Not the  most quickest method, but alleviates _**some**_ of the hard crashes we were having during rendering
- Added some comments on why some stuff are done in the code incase they are seen by someone else
- Added a render operation to render from starting frame always, solves some odd exploding rigify rigs. (simple starts from the  smallest frame before rendering)
- Make sure that if use_lock_interface is disabled, there is NOT accident for the plugin to start doing the baking per frame even if the boolean is turned on for the mesh. This was previously possible.

### CODE REVIEW

**Comment by sentharn** [comment]
I'll take a look in the next few days, but so far it looks like some great cleanup and stability fixes. My own plugin was crashing my renders recently, so it's appreciated. ;)

Out of curiosity, is the video available publicly? I'd love to see what people are doing with the addon. An "as seen in" section on the readme might be cool too. I don't want it to get huge though...this is already getting more attention than I'd planned...

**Comment by Menithal** [comment]
The videos are not (yet) available for public (the convention is  still on going; they may appear at somepoint), It was streamed with some odd stream audio issue but stuff like https://m.twitch.tv/emirpfe/clip/SucculentHyperVultureChefFrank-5_hU5fAjS_buJvZN

**Review by sentharn — APPROVED** [review]
Looks great. Thank you for spending the time on this and I appreciate your patience while I looked at it.

Animating from the UI doesn't force a frame update to frame start? Is something left over from the viewport state? Interesting. It'd be nice if we could hook directly into the render op but I feel like I'm playing with fire already. There's one side effect now; the user is left at starting frame after hitting animate now. We could save and restore the frame # in execute() I suppose. Up to you. I don't have any test case to see if it works or not.

I'm glad the plugin was useful for you. Feel free to add yourself to the README Credit section for fixes.

I hope the full video gets posted someday! It looks very well made.

**Comment by sentharn** [comment]
Merges in fixes from @Menithal to improve stability and memory usage.

Rendering from the UI should now be done using a new "Render Animation with Encoded Normals" menu option. Alternatively, ensure the viewport is on the same frame as the starting frame before animating.

**Pull request merged**
